name: inet-service

services:
  inet-service:
    build:
      context: .
      args:
        - ROUTER_IP=192.168.3.2
    restart: always
    environment:
      UVICORN_APP: "src.main:app"
      UVICORN_HOST: "0.0.0.0"
      UVICORN_PORT: "8000"
      DB_HOST: mariadb
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: sqli_lab
      FLAG: ISIP{TEST_FLAG}
    depends_on:
      mariadb:
        condition: service_healthy
    cap_add:
      - NET_ADMIN
    networks:
      inet:
        ipv4_address: 192.168.3.10

  mariadb:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sqli_lab
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      inet:
        ipv4_address: 192.168.3.20
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  inet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.3.0/24
